const MTCA_SCHEDULE = [
  {"title":"LIKE OTHER GIRLS FROM DADDY LONG LEGS","date":"2026-02-06","start":"09:30","end":"","location":"MEZZ 10","speaker":"Lucy Johnson","type":"SOLO"},
  {"title":"LOST AND FOUND BY DORI APPEL","date":"2026-02-06","start":"09:30","end":"","location":"LIDO A","speaker":"Riley Beres","type":"MONO"},
  {"title":"SAFER FROM FIRST DATE","date":"2026-02-06","start":"09:45","end":"","location":"MEZZ 9","speaker":"Ivy Ries-Kinney","type":"SOLO"},
  {"title":"I WANT TO GO BACK FROM THE NOTEBOOK","date":"2026-02-06","start":"09:45","end":"","location":"CARMEL","speaker":"Juliana Montalvo, Mia Montalvo","type":"DUET"},
  {"title":"GO! FROM FREAKY FRIDAY","date":"2026-02-06","start":"10:00","end":"","location":"MEZZ 8","speaker":"Weston Richardson","type":"SOLO"},
  {"title":"GO BULLDOGS BY LEAH MANN","date":"2026-02-06","start":"10:00","end":"","location":"BALBOA B","speaker":"Fehr Lewis","type":"MONO"},
  {"title":"USEFUL FROM OPERATION MINCEMEAT","date":"2026-02-06","start":"10:15","end":"","location":"CARMEL","speaker":"Liam Mckaig, Presley Emory","type":"DUET"},
  {"title":"BREATHE FROM IN THE HEIGHTS","date":"2026-02-06","start":"10:30","end":"","location":"MEZZ 6","speaker":"Juliana Montalvo","type":"SOLO"},
  {"title":"MONOLOGUE SHOW FROM HELL (LOLA) BY DON ZOLODIS","date":"2026-02-06","start":"10:45","end":"","location":"BALBOA C","speaker":"Delaney Saunders","type":"MONO"},
  {"title":"MAYBE HE LIKES ME FROM THE MAN IN THE CEILING","date":"2026-02-06","start":"10:45","end":"","location":"MEZZ 11","speaker":"Graham Henderson","type":"SOLO"},
  {"title":"GREASE GOT A HOLD FROM THE OUTSIDERS","date":"2026-02-06","start":"10:45","end":"","location":"AVILA A","speaker":"Liam Mckaig","type":"DANCE"},
  {"title":"SOMEBODY TO LOVE FROM WE WILL ROCK YOU","date":"2026-02-06","start":"10:45","end":"","location":"MEZZ 9","speaker":"Fehr Lewis","type":"SOLO"},
  {"title":"RUN AWAY WITH ME FROM THE MAD ONES","date":"2026-02-06","start":"11:00","end":"","location":"MEZZ 3","speaker":"Tyler Harding","type":"SOLO"},
  {"title":"I SEE STARS FROM MEAN GIRLS","date":"2026-02-06","start":"11:00","end":"","location":"MONTERREY","speaker":"Cannady Wood, Meghan Wallace","type":"DUET"},
  {"title":"OLIVER","date":"2026-02-06","start":"11:30","end":"","location":"PACIFIC C/D","speaker":"OLIVER","type":"GROUP"},
  {"title":"GIA'S LAMENT FROM LITTLE MISS PERFECT","date":"2026-02-06","start":"13:00","end":"","location":"MEZZ 9","speaker":"Presley Emory","type":"SOLO"},
  {"title":"NO SUBSTITUES BY DON ZOLODIS","date":"2026-02-06","start":"13:30","end":"","location":"LIDO C","speaker":"Avery Beres","type":"MONO"},
  {"title":"ANOTHER WORLD FROM THE LITTLE PRINCESS","date":"2026-02-06","start":"15:15","end":"","location":"MEZZ 12","speaker":"Meghan Wallace","type":"SOLO"},
  {"title":"REMEMBER THIS FROM THE MAD ONES","date":"2026-02-06","start":"15:30","end":"","location":"CARMEL","speaker":"Gabbi Ward, Jack Hill","type":"DUET"},
  {"title":"BARABARA 2.0 FROM BEETLEJUICE","date":"2026-02-06","start":"15:45","end":"","location":"MEZZ 4","speaker":"Alice Wallace","type":"SOLO"},
  {"title":"TOP SECRET PERSONAL BEESWAX FROM JUNIE B JONES","date":"2026-02-06","start":"16:00","end":"","location":"MEZZ 13","speaker":"Emmy Beres","type":"SOLO"},
  {"title":"DEAD MOM FROM BEETLEJUICE","date":"2026-02-06","start":"16:15","end":"","location":"MEZZ 12","speaker":"Piper Mellow","type":"SOLO"},
  {"title":"JEREMY FROM THE MONOLOGUE SHOW FROM HELL BY DON ZOLIDIS","date":"2026-02-06","start":"16:15","end":"","location":"LIDO B","speaker":"Tyler Harding","type":"MONO"},
  {"title":"THE LIFE I NEVER LED FROM SISTER ACT","date":"2026-02-06","start":"16:45","end":"","location":"MEZZ 10","speaker":"Eva Barlow","type":"SOLO"},
  {"title":"EXTRAORDINARY FROM PIPPIN","date":"2026-02-06","start":"16:45","end":"","location":"MEZZ 8","speaker":"Liam Mckaig","type":"SOLO"},
  {"title":"SAME BUT DIFFERENT FROM ISLANDERS","date":"2026-02-06","start":"16:45","end":"","location":"MONTERREY","speaker":"Nadia Russell, Presley Emory","type":"DUET"},
  {"title":"GOTTA GET OUT FROM ORDINARY DAYS","date":"2026-02-06","start":"17:00","end":"","location":"MEZZ 6","speaker":"Avery Beres","type":"SOLO"},
  {"title":"WHAT YOU MEAN TO ME FROM FINDING NEVERLAND","date":"2026-02-06","start":"17:45","end":"","location":"SAN SIM B","speaker":"Alice Wallace, Blake Franklin","type":"DUET"},
  {"title":"BLOOM FROM IN PIECES","date":"2026-02-06","start":"19:15","end":"","location":"SAN SIM B","speaker":"Avery Beres, Owen Henderson","type":"DUET"},
  {"title":"ALL THAT MATTERS NOW FROM FINDING NEVERLAND","date":"2026-02-07","start":"08:15","end":"","location":"MEZZ 6","speaker":"Anna Bare","type":"SOLO"},
  {"title":"WAY BACK TO THEN FROM TITLE OF SHOW","date":"2026-02-07","start":"08:30","end":"","location":"AVILA B","speaker":"Kennedy Pilkington","type":"DANCE"},
  {"title":"CALM COOL AND COLLECTED FROM CALVIN BERGER","date":"2026-02-07","start":"08:30","end":"","location":"SAN SIM A","speaker":"Ashley Rachlin, Caroline Frampton","type":"DUET"},
  {"title":"WALLS FROM SHUCKED","date":"2026-02-07","start":"08:45","end":"","location":"MEZZ 9","speaker":"Lucy Bennett","type":"SOLO"},
  {"title":"SAFER FROM FIRST DATE","date":"2026-02-07","start":"09:00","end":"","location":"MEZZ 7","speaker":"Mia Montalvo","type":"SOLO"},
  {"title":"THIS IS NOT OVER FROM PARADE","date":"2026-02-07","start":"09:00","end":"","location":"MEZZ 6","speaker":"Owen Henderson","type":"SOLO"},
  {"title":"ADOLPHO FROM THE DROWSY CHAPERONE","date":"2026-02-07","start":"09:00","end":"","location":"MEZZ 5","speaker":"Giles Gorski","type":"SOLO"},
  {"title":"KEY EXCHANGE BY KEVIN WADE","date":"2026-02-07","start":"09:00","end":"","location":"LIDO A","speaker":"Caroline Frampton","type":"MONO"},
  {"title":"THE HISTORY OF WRONG GUYS FROM KINKY BOOTS","date":"2026-02-07","start":"09:15","end":"","location":"MEZZ 6","speaker":"Avery Parker","type":"SOLO"},
  {"title":"ME AND YOU BUT MOSTLY ME FROM BOOK OF MORMON","date":"2026-02-07","start":"09:15","end":"","location":"CARMEL","speaker":"Bryan Lewis, Liam Mckaig","type":"DUET"},
  {"title":"MORE THAN MEETS THE EYE FROM CALVIN BERGER","date":"2026-02-07","start":"09:30","end":"","location":"MEZZ 8","speaker":"Delaney Saunders","type":"SOLO"},
  {"title":"LITTLE BROTHER FROM THE OUTSIDERS","date":"2026-02-07","start":"09:30","end":"","location":"MEZZ 7","speaker":"Jack Hill","type":"SOLO"},
  {"title":"NOTICE ME HORTON FROM SEUSSICAL","date":"2026-02-07","start":"09:30","end":"","location":"MEZZ 10","speaker":"Bailey Beres","type":"SOLO"},
  {"title":"ALYSSA FROM THE MONOLGUE SHOW FROM HELL BY DON ZOLIDIS","date":"2026-02-07","start":"09:30","end":"","location":"BALBOA B","speaker":"Nadia Russell","type":"MONO"},
  {"title":"THE COLD SHOULDER: I'LL STOP THIS CAR BY LEAH MANN","date":"2026-02-07","start":"09:45","end":"","location":"BALBOA A","speaker":"Cannady Wood","type":"MONO"},
  {"title":"FACADE","date":"2026-02-07","start":"10:20","end":"","location":"CALI B","speaker":"FACADE","type":"GROUP"},
  {"title":"HERE'S MY PLAN FROM ADVENTURES OF TOM SAWYER","date":"2026-02-07","start":"11:00","end":"","location":"MEZZ 10","speaker":"Kingston Feind","type":"SOLO"},
  {"title":"ALL FALLS DOWN FROM CHAPLIN","date":"2026-02-07","start":"11:45","end":"","location":"MEZZ 9","speaker":"Sloan Arnold","type":"SOLO"},
  {"title":"RAINING FROM ROCKY","date":"2026-02-07","start":"13:15","end":"","location":"AVILA B","speaker":"Ashley Rachlin","type":"DANCE"},
  {"title":"WHEN WORDS FAIL FROM SHREK","date":"2026-02-07","start":"13:15","end":"","location":"MEZZ 8","speaker":"Bryan Lewis","type":"SOLO"},
  {"title":"I COULDN'T KNOW SOMEONE LESS FROM DADDY LONG LEGS","date":"2026-02-07","start":"13:15","end":"","location":"MEZZ 3","speaker":"Ava Swanger","type":"SOLO"},
  {"title":"PHANTOM OF THE OPERA","date":"2026-02-07","start":"13:15","end":"","location":"BALBOA C","speaker":"Riley Beres","type":"HAIR"},
  {"title":"FREEDOM FIGHTER","date":"2026-02-07","start":"13:30","end":"","location":"BALBOA A","speaker":"Emmy Beres","type":"MONO"},
  {"title":"THE CHEERIO WARS BY GABRIEL DAVIS","date":"2026-02-07","start":"13:30","end":"","location":"LIDO C","speaker":"Giles Gorski","type":"MONO"},
  {"title":"ONE PERFECT MOMENT FROM BRING IT ON","date":"2026-02-07","start":"13:30","end":"","location":"MEZZ 12","speaker":"Cannady Wood","type":"SOLO"},
  {"title":"1980S MUSICALS BRITISH INVASION","date":"2026-02-07","start":"14:00","end":"","location":"CALI C","speaker":"STAR WARS","type":"GROUP"},
  {"title":"ANYWHERE BUT HERE FROM HONEYMOON IN VEGAS","date":"2026-02-07","start":"15:00","end":"","location":"MEZZ 2","speaker":"Riley Beres","type":"SOLO"},
  {"title":"IT COULD TOTALLY HAPPEN FROM LIKE YOU LIKE IT","date":"2026-02-07","start":"15:00","end":"","location":"CARMEL","speaker":"Giles Gorski, Juliana Montalvo","type":"DUET"},
  {"title":"LUNCH HOUR BY JEAN KERR","date":"2026-02-07","start":"15:15","end":"","location":"LIDO A","speaker":"Ashley Rachlin","type":"MONO"},
  {"title":"FOR FOREVER FROM DEAR EVAN HANSEN","date":"2026-02-07","start":"15:30","end":"","location":"MEZZ 4","speaker":"Blake Franklin","type":"SOLO"},
  {"title":"COMIC BOOK KIND OF LOVE FROM EUGENIUS THE MUSICAL","date":"2026-02-07","start":"15:30","end":"","location":"MONTERREY","speaker":"Fehr Lewis, William Parker","type":"DUET"},
  {"title":"TOO MUCH WORK BY BLESSING DUSSEY","date":"2026-02-07","start":"16:15","end":"","location":"BALBOA B","speaker":"Amelia Smith","type":"MONO"},
  {"title":"THE LAMEST PLACE IN THE WORLD FROM 13","date":"2026-02-07","start":"16:45","end":"","location":"MEZZ 1","speaker":"Ashley Rachlin","type":"SOLO"},
  {"title":"LIVE OUT LOUD FROM THE LITTLE PRINCESS","date":"2026-02-07","start":"16:45","end":"","location":"MEZZ 11","speaker":"Abby Steed","type":"SOLO"},
  {"title":"I SPEAK SIX LANGUAGES FROM SPELLING BEE","date":"2026-02-07","start":"17:30","end":"","location":"MEZZ 12","speaker":"Olivia Hunt","type":"SOLO"}
];
